version: '3.7'

networks:
#This isnt needed unless you need multiple containers to talk to each other
  taxnet:
    driver: bridge
    ipam:
      config:
        - subnet: 100.42.0.0/16

services:

  flask-api:
    hostname: flask-api
    build: ./flask-api/.
    container_name: flask-api
    restart: 'always'
    expose: 
      - '5000'
    ports:
      - '5000:5000'
    environment:
      FLASK_HOST: '0.0.0.0'
      FLASK_PORT: 5000
      DEBUG_FLASK: null
      ENDPOINT: '/v1'
      ETHERSCAN: 
    networks:
      - taxnet



  nginx:
    container_name: nginx-router
    hostname: nginx
    build: ./nginx/
    restart: 'always'
    expose:
      - 80
    ports:
      - 80:80
    environment:
      FLASK_PORT: 5000
      API_ENDPOINT: '/api'
    volumes: 
      - ./app/build/:/usr/share/nginx/html:cached
      - ./nginx/logs/:/logs:cached
    networks:
      - taxnet

volumes:
  pgadmin: